### ISSUE TITLE
需求：解耦

### ISSUE THREAD

**Issue by 10xhunter** [rooch-network/rooch-clicker#1]
```
<QueryClientProvider client={queryClient}>
      <RoochProvider networks={networkConfig} defaultNetwork="testnet">
        <WalletProvider chain={"bitcoin"} autoConnect>
          <App />
        </WalletProvider>
      </RoochProvider>
</QueryClientProvider>

import {
  UseSignAndExecuteTransaction,
  useConnectWallet[强依赖？],,
  useCreateSessionKey,
  useCurrentAddress,
  useCurrentSession,
  useRemoveSession,
  useRoochClientQuery[强依赖？],
  useWalletStore[强依赖？],,
  useWallets[强依赖？],,
} from "@roochnetwork/rooch-sdk-kit";
```
我在用 [web3auth](https://github.com/Web3Auth/web3auth-core-kit-examples/tree/main/single-factor-auth-web/sfa-web-bitcoin-example) 改的时候，发现耦合性太高了，只用 RoochProvider 结合 web3auth 能否实现 rooch-clicker 呢？

谢谢

**Comment by wow-sven** [comment]
provider 目前是钱包和rooch-sdk 的工具集，可以用直接使用rooch-sdk 来做这个需求，sdk-kit 支持非钱包类的集成还需要调研一下，太多了第三方库了。

**Comment by 10xhunter** [comment]
> provider 目前是钱包和rooch-sdk 的工具集，可以用直接使用rooch-sdk 来做这个需求，sdk-kit 支持非钱包类的集成还需要调研一下，太多了第三方库了。

好的，我试试，谢谢
